""" Make changes to status

Revision ID: 346e45514ec6
Revises: 65508b452b3b
Create Date: 2025-08-29 18:41:31.923850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346e45514ec6'
down_revision: Union[str, None] = '65508b452b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_orders', schema=None) as batch_op:
        batch_op.alter_column('product_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('quantity',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('supplier_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('supplier_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('quantity',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('product_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###